import pygame.image

class Image():
    def __init__(self):
        self.bg_pic = pygame.image.load("./images/bg.png")
        self.rect = self.bg_pic.get_rect()
        self.bird_0 = pygame.image.load("./images/bird0.png")
        self.bird_1 = pygame.image.load("./images/bird1.png")
        self.bird_2 = pygame.image.load("./images/bird2.png")
        self.zero = pygame.image.load("./images/0.png")
        self.one = pygame.image.load("./images/1.png")
        self.two = pygame.image.load("./images/2.png")
        self.three = pygame.image.load("./images/3.png")
        self.four = pygame.image.load("./images/4.png")
        self.five = pygame.image.load("./images/5.png")
        self.six = pygame.image.load("./images/6.png")
        self.seven = pygame.image.load("./images/7.png")
        self.eight = pygame.image.load("./images/8.png")
        self.nine = pygame.image.load("./images/9.png")
        self.gameover = pygame.image.load("./images/gameover.png")
        self.getready = pygame.image.load("./images/getready.png")
        self.land = pygame.image.load("./images/land.png")
        self.medal_0 = pygame.image.load("./images/medal0.png")
        self.medal_1 = pygame.image.load("./images/medal1.png")
        self.medal_2 = pygame.image.load("./images/medal2.png")
        self.medal_3 = pygame.image.load("./images/medal3.png")
        self.pipe_down = pygame.image.load("./images/pipe_down.png")
        self.pipe_up = pygame.image.load("./images/pipe_up.png")
        self.score = pygame.image.load("./images/score.png")
        self.start_pic = pygame.image.load("./images/start_pic.png")
        self.title_pic = pygame.image.load("./images/title.png")
        self.restart = pygame.image.load("./images/restart.png")
